name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Node.jobs
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependecies
        run: npm install
      - name: Run tests
        run: npm test
